
version: '3'
services:
  jupyter-tutorial:
    build: ./dfile/note/
    container_name: m09.jupyter
    user: root
    environment:
      - GRANT_SUDO=yes
      - aws_access_key_id='anything'
      - aws_secret_access_key='anything'
      - region_name='ap-northeast-1'
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./note/:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''

  db1:
    image: mariadb
    container_name: cc104.rds.local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hahaha
    volumes:
      - ./data_mariadb/:/var/lib/mysql

  db2:
    image: mysql
    container_name: m10.cc104.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hahaha
    volumes:
      - ./data_mysql/:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  dynamodb:
    build: ./dfile/dynamo/
    container_name: cc104.dynamodb.local
    volumes:
      - ./data_dynamo:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath ./data

  fakes3:
    build: ./dfile/s3/
    container_name: cc104.s3.local
    ports:
      - "4569:4569"
    volumes:
      - ./data_s3:/fakes3_root

  sns:
    image: s12v/sns
    container_name: cc104.sns.local
    ports:
      - "9911:9911"
    volumes:
      - ./config_sns:/etc/sns/
    depends_on:
      - sqs

  sqs:
    image: s12v/elasticmq
    container_name: cc104.sqs2.local
    ports:
      - "9324:9324"
    volumes:
      - ./config_sqs:/etc

